// Packs the sprites listed in assets/manifest.json into one atlas and writes
// src/ui/gfx/atlas.gen.ts (a base64 PNG plus the frame table). Every sprite
// gets the house style on the way: a 1px black outline around its pixels, so
// art from different CC0 packs reads as one game.
//
//   node tools/pack-assets.mjs        (npm run assets)
//
// manifest.json:
//   { "sheets": { "<id>": "assets/<pack>/<file>.png" },
//     "sprites": { "<name>": { "sheet": "<id>", "x": 0, "y": 0, "w": 16, "h": 16,
//                              "frames": 1, "dx": 16, "outline": true } } }
// Frames are read left to right, `dx` apart (default: w). Output order is stable.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import pngjs from "pngjs";

const { PNG } = pngjs;
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(join(root, "assets/manifest.json"), "utf8"));
const OUT = join(root, "src/ui/gfx/atlas.gen.ts");
const ATLAS_W = 1024;

const sheets = {};
for (const [id, file] of Object.entries(manifest.sheets)) sheets[id] = PNG.sync.read(readFileSync(join(root, file)));

/** One frame cut out of a sheet, grown by 1px each side, outlined in black. */
function cut(sheet, x, y, w, h, outline) {
    const pad = outline ? 1 : 0, W = w + pad * 2, H = h + pad * 2;
    const px = new Uint8Array(W * H * 4);
    const src = (sx, sy) => {
        if (sx < 0 || sy < 0 || sx >= sheet.width || sy >= sheet.height) return null;
        const i = (sy * sheet.width + sx) * 4;
        return sheet.data[i + 3] > 24 ? sheet.data.subarray(i, i + 4) : null;
    };
    for (let j = 0; j < H; j++) for (let i = 0; i < W; i++) {
        const o = (j * W + i) * 4, c = src(x + i - pad, y + j - pad);
        if (c) { px[o] = c[0]; px[o + 1] = c[1]; px[o + 2] = c[2]; px[o + 3] = 255; continue; }
        if (!outline) continue;
        let edge = false;
        for (const [ox, oy] of [[-1, 0], [1, 0], [0, -1], [0, 1]]) {
            const ii = i - pad + ox, jj = j - pad + oy;
            if (ii >= 0 && jj >= 0 && ii < w && jj < h && src(x + ii, y + jj)) { edge = true; break; }
        }
        if (edge) { px[o] = 17; px[o + 1] = 17; px[o + 2] = 17; px[o + 3] = 255; }
    }
    return { w: W, h: H, px };
}

// Cut everything, then shelf-pack tallest first.
const cuts = [];
for (const [name, s] of Object.entries(manifest.sprites)) {
    const sheet = sheets[s.sheet];
    if (!sheet) throw new Error(`${name}: unknown sheet ${s.sheet}`);
    const n = s.frames ?? 1, dx = s.dx ?? s.w;
    const frames = [];
    for (let f = 0; f < n; f++) frames.push(cut(sheet, s.x + f * dx, s.y, s.w, s.h, s.outline !== false));
    cuts.push({ name, frames, w: frames[0].w, h: frames[0].h });
}
const order = [...cuts].sort((a, b) => b.h - a.h || a.name.localeCompare(b.name));
let cx = 0, cy = 0, rowH = 0;
const table = {};
const placed = [];
for (const c of order) {
    for (let f = 0; f < c.frames.length; f++) {
        if (cx + c.w > ATLAS_W) { cx = 0; cy += rowH + 1; rowH = 0; }
        placed.push({ x: cx, y: cy, fr: c.frames[f] });
        if (f === 0) table[c.name] = { x: cx, y: cy, w: c.w, h: c.h, n: c.frames.length };
        cx += c.w + 1; rowH = Math.max(rowH, c.h);
    }
}
// Frames of one sprite must sit side by side: re-check and fail loudly if a row broke them.
for (const c of cuts) {
    const t = table[c.name];
    const run = placed.filter(p => c.frames.includes(p.fr));
    run.forEach((p, i) => { if (p.y !== t.y || p.x !== t.x + i * (c.w + 1)) throw new Error(`${c.name}: frames wrapped a row; raise ATLAS_W`); });
}
if (!placed.length) {
    writeFileSync(OUT, `// Generated by tools/pack-assets.mjs from assets/manifest.json. Do not edit.

export interface Frame { x: number; y: number; w: number; h: number; n: number }
export const FRAMES: Record<string, Frame> = {};
export const ATLAS_PNG = "";
`);
    console.log("no sprites in the manifest: wrote an empty atlas");
    process.exit(0);
}
const atlas = new PNG({ width: ATLAS_W, height: cy + rowH });
atlas.data.fill(0);
for (const p of placed) for (let j = 0; j < p.fr.h; j++) {
    const s = j * p.fr.w * 4, d = ((p.y + j) * ATLAS_W + p.x) * 4;
    atlas.data.set(p.fr.px.subarray(s, s + p.fr.w * 4), d);
}
const b64 = PNG.sync.write(atlas, { colorType: 6 }).toString("base64");
const sorted = Object.fromEntries(Object.keys(table).sort().map(k => [k, table[k]]));
writeFileSync(OUT, `// Generated by tools/pack-assets.mjs from assets/manifest.json. Do not edit.
// Art: CC0 packs listed in assets/CREDITS.md.

export interface Frame { x: number; y: number; w: number; h: number; n: number }
export const FRAMES: Record<string, Frame> = ${JSON.stringify(sorted)};
export const ATLAS_PNG = "data:image/png;base64,${b64}";
`);
console.log(`atlas ${ATLAS_W}x${cy + rowH}, ${cuts.length} sprites, ${placed.length} frames, ${(b64.length / 1024).toFixed(0)} KiB base64`);
