// Packs the sprites listed in assets/manifest.json into one atlas and writes
// src/ui/gfx/atlas.gen.ts (a base64 PNG plus the frame table). Every sprite
// gets the house style on the way: a 1px black outline around its pixels, so
// art from different CC0 packs reads as one game.
//
//   node tools/fetch-assets.mjs   (once: downloads the packs into assets/.cache)
//   node tools/pack-assets.mjs    (npm run assets)
//
// manifest.json:
//   "roots":   { "P": "assets/.cache/<folder>" }        path aliases ("P:/file.png")
//   "sprites": { "<name>": source + options }
//     source:  { "sheet": "P:/a.png", "w": 38, "h": 48, "frames": 4, "x": 0, "y": 0, "dx": 38 }
//          or  { "files": ["P:/idle1.png", ...] }  or  { "files": "P:/idle{1-6}.png" }
//     options: "down": 2 (shrink by a whole factor), "faces": "left" (default "right"),
//              "order": [0, 1, 2, 1] (play the frames in this order: RPG-maker walks),
//              "outline": false, "trim": false, "alpha": true (keep soft alpha: backgrounds)
// Frames of a sprite are trimmed to their common bounding box, so they stay
// aligned. Each sprite records its anchor: the middle of its feet in frame 0
// (ax, ay), which the game puts on the ground.
//
// The atlas ships as an 8-bit palette PNG: the packs share a few hundred
// colours, so the rarest ones are folded into their nearest neighbour until
// 255 remain (no new colours are made), plus one transparent entry. That is
// about half the size of the full-colour PNG for no visible change.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { deflateSync, constants as zc } from "node:zlib";
import pngjs from "pngjs";

const { PNG } = pngjs;
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(join(root, "assets/manifest.json"), "utf8"));
const OUT = join(root, "src/ui/gfx/atlas.gen.ts");
const ATLAS_W = 1024;
const HEADER = "// Generated by tools/pack-assets.mjs from assets/manifest.json. Do not edit.\n// Art: CC0 / public-domain packs listed in assets/CREDITS.md.\n\n"
    + "/** ax, ay: the feet in frame-local pixels; f: 1 if the art faces left. */\n"
    + "export interface Frame { x: number; y: number; w: number; h: number; n: number; ax: number; ay: number; f: number }\n";

const resolve = p => {
    const m = /^(\w+):(.*)$/.exec(p);
    return join(root, m && manifest.roots?.[m[1]] ? manifest.roots[m[1]] + m[2] : p);
};
const sheets = new Map();
function sheet(p) {
    const full = resolve(p);
    if (!sheets.has(full)) {
        if (!existsSync(full)) throw new Error(`missing ${full} - run node tools/fetch-assets.mjs`);
        // Old PNGs (the Dungeon Crawl set) repeat IEND at the end, which pngjs rejects:
        // walk the chunks and cut the file after the first IEND.
        let buf = readFileSync(full);
        for (let p = 8; p + 8 <= buf.length;) {
            const len = buf.readUInt32BE(p), type = buf.toString("latin1", p + 4, p + 8);
            p += 12 + len;
            if (type === "IEND") { buf = buf.subarray(0, p); break; }
        }
        sheets.set(full, PNG.sync.read(buf));
    }
    return sheets.get(full);
}
/** "a{1-6}.png" -> ["a1.png", ... "a6.png"] */
const expand = f => {
    if (Array.isArray(f)) return f;
    const m = /\{(\d+)-(\d+)\}/.exec(f);
    if (!m) return [f];
    const out = [];
    for (let i = Number(m[1]); i <= Number(m[2]); i++) out.push(f.replace(m[0], String(i)));
    return out;
};

/** RGBA frame as { w, h, px } from a sheet rectangle. Sprites snap alpha to on/off; backgrounds keep it. */
function grab(img, x, y, w, h, keepAlpha = false) {
    const px = new Uint8Array(w * h * 4);
    for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) {
        const sx = x + i, sy = y + j;
        if (sx >= img.width || sy >= img.height) continue;
        const s = (sy * img.width + sx) * 4, d = (j * w + i) * 4;
        if (keepAlpha) px.set(img.data.subarray(s, s + 4), d);
        else if (img.data[s + 3] > 24) { px[d] = img.data[s]; px[d + 1] = img.data[s + 1]; px[d + 2] = img.data[s + 2]; px[d + 3] = 255; }
    }
    return { w, h, px };
}
/** Shrink by a whole factor: each block becomes its most-covered opaque pixel. */
function down(fr, k) {
    const w = Math.ceil(fr.w / k), h = Math.ceil(fr.h / k), px = new Uint8Array(w * h * 4);
    for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) {
        let n = 0, pick = -1;
        for (let b = 0; b < k; b++) for (let a = 0; a < k; a++) {
            const x = i * k + a, y = j * k + b;
            if (x >= fr.w || y >= fr.h) continue;
            const s = (y * fr.w + x) * 4;
            if (fr.px[s + 3]) { n++; if (pick < 0 || (a === 0 && b === 0)) pick = s; }
        }
        if (n * 2 >= k * k && pick >= 0) px.set(fr.px.subarray(pick, pick + 4), (j * w + i) * 4);
    }
    return { w, h, px };
}
const opaque = (fr, x, y) => x >= 0 && y >= 0 && x < fr.w && y < fr.h && fr.px[(y * fr.w + x) * 4 + 3] > 0;
function crop(fr, x0, y0, w, h) {
    const px = new Uint8Array(w * h * 4);
    for (let j = 0; j < h; j++) for (let i = 0; i < w; i++) if (opaque(fr, x0 + i, y0 + j)) px.set(fr.px.subarray(((y0 + j) * fr.w + x0 + i) * 4, ((y0 + j) * fr.w + x0 + i) * 4 + 4), (j * w + i) * 4);
    return { w, h, px };
}
/** Grow by 1px and draw a black outline around the opaque pixels. */
function outline(fr) {
    const W = fr.w + 2, H = fr.h + 2, px = new Uint8Array(W * H * 4);
    for (let j = 0; j < H; j++) for (let i = 0; i < W; i++) {
        const o = (j * W + i) * 4;
        if (opaque(fr, i - 1, j - 1)) { px.set(fr.px.subarray(((j - 1) * fr.w + i - 1) * 4, ((j - 1) * fr.w + i - 1) * 4 + 4), o); continue; }
        if (opaque(fr, i - 2, j - 1) || opaque(fr, i, j - 1) || opaque(fr, i - 1, j - 2) || opaque(fr, i - 1, j)) { px[o] = 17; px[o + 1] = 17; px[o + 2] = 17; px[o + 3] = 255; }
    }
    return { w: W, h: H, px };
}

const cuts = [];
for (const [name, s] of Object.entries(manifest.sprites)) {
    let frames;
    if (s.files) frames = expand(s.files).map(f => { const img = sheet(f); return grab(img, 0, 0, img.width, img.height, s.alpha); });
    else {
        const img = sheet(s.sheet), w = s.w ?? img.width, h = s.h ?? img.height;
        const n = s.frames ?? Math.floor((img.width - (s.x ?? 0)) / (s.dx ?? w)), dx = s.dx ?? w;
        frames = [];
        for (let f = 0; f < n; f++) frames.push(grab(img, (s.x ?? 0) + f * dx, s.y ?? 0, w, h, s.alpha));
    }
    if (s.order) frames = s.order.map(i => { if (!frames[i]) throw new Error(`${name}: no frame ${i}`); return frames[i]; });
    if (s.down > 1) frames = frames.map(fr => down(fr, s.down));
    if (s.trim !== false) {
        // Common bounding box of all frames, so the animation doesn't jitter.
        let x0 = Infinity, y0 = Infinity, x1 = -1, y1 = -1;
        for (const fr of frames) for (let y = 0; y < fr.h; y++) for (let x = 0; x < fr.w; x++) if (opaque(fr, x, y)) { x0 = Math.min(x0, x); y0 = Math.min(y0, y); x1 = Math.max(x1, x); y1 = Math.max(y1, y); }
        if (x1 < 0) throw new Error(`${name}: empty`);
        frames = frames.map(fr => crop(fr, x0, y0, x1 - x0 + 1, y1 - y0 + 1));
    }
    // Anchor: the feet of frame 0 - the middle of the opaque pixels in its lowest rows.
    const f0 = frames[0];
    let bottom = f0.h - 1;
    while (bottom > 0 && ![...Array(f0.w).keys()].some(x => opaque(f0, x, bottom))) bottom--;
    let sum = 0, cnt = 0;
    for (let y = Math.max(0, bottom - 3); y <= bottom; y++) for (let x = 0; x < f0.w; x++) if (opaque(f0, x, y)) { sum += x; cnt++; }
    const pad = s.outline !== false ? 1 : 0;
    if (s.outline !== false) frames = frames.map(outline);
    cuts.push({ name, frames, w: frames[0].w, h: frames[0].h, ax: Math.round((cnt ? sum / cnt : f0.w / 2) + pad), ay: bottom + 1 + pad, f: s.faces === "left" ? 1 : 0 });
}

if (!cuts.length) {
    writeFileSync(OUT, HEADER + "export const FRAMES: Record<string, Frame> = {};\nexport const ATLAS_PNG = \"\";\n");
    console.log("no sprites in the manifest: wrote an empty atlas");
    process.exit(0);
}

// Shelf-pack, tallest first; a sprite's frames stay side by side in one row.
const order = [...cuts].sort((a, b) => b.h - a.h || a.name.localeCompare(b.name));
let cx = 0, cy = 0, rowH = 0;
const table = {}, placed = [];
for (const c of order) {
    const need = c.frames.length * (c.w + 1);
    if (need > ATLAS_W) throw new Error(`${c.name}: ${c.frames.length} frames of ${c.w}px don't fit a ${ATLAS_W}px row`);
    if (cx + need > ATLAS_W) { cx = 0; cy += rowH + 1; rowH = 0; }
    table[c.name] = { x: cx, y: cy, w: c.w, h: c.h, n: c.frames.length, ax: c.ax, ay: c.ay, f: c.f };
    for (const fr of c.frames) { placed.push({ x: cx, y: cy, fr }); cx += c.w + 1; }
    rowH = Math.max(rowH, c.h);
}
const atlas = new PNG({ width: ATLAS_W, height: cy + rowH });
atlas.data.fill(0);
for (const p of placed) for (let j = 0; j < p.fr.h; j++) atlas.data.set(p.fr.px.subarray(j * p.fr.w * 4, (j + 1) * p.fr.w * 4), ((p.y + j) * ATLAS_W + p.x) * 4);
const pal = palettePng(atlas);
const b64 = pal.png.toString("base64");
const sorted = Object.fromEntries(Object.keys(table).sort().map(k => [k, table[k]]));
writeFileSync(OUT, HEADER + `export const FRAMES: Record<string, Frame> = ${JSON.stringify(sorted, null, 0).replace(/\},"/g, '},\n  "')};\n`
    + `export const ATLAS_PNG = "data:image/png;base64,${b64}";\n`);
console.log(`atlas ${ATLAS_W}x${cy + rowH}, ${cuts.length} sprites, ${placed.length} frames, ${pal.colours} of ${pal.source} colours, ${(b64.length / 1024).toFixed(0)} KiB base64`);

/**
 * RGBA image -> 8-bit palette PNG. Alpha must be all-or-nothing (the packer's
 * outline pass makes it so; soft-alpha backgrounds are flattened at 50%).
 * Palette entry 0 is transparent. Above 255 colours, the colour with the
 * smallest (pixels x distance to its nearest neighbour) is folded into that
 * neighbour, repeatedly: frequent colours stay exact, rare near-duplicates go.
 */
function palettePng(img) {
    const { width: w, height: h, data } = img;
    const index = new Map(), R = [], G = [], B = [], cnt = [];
    for (let i = 0; i < data.length; i += 4) {
        if (data[i + 3] < 128) continue;
        const k = (data[i] << 16) | (data[i + 1] << 8) | data[i + 2];
        let c = index.get(k);
        if (c === undefined) { c = R.length; index.set(k, c); R.push(data[i]); G.push(data[i + 1]); B.push(data[i + 2]); cnt.push(0); }
        cnt[c]++;
    }
    const n = R.length;
    // "Redmean": a cheap distance closer to what the eye sees than plain RGB.
    const dist = (a, b) => {
        const rm = (R[a] + R[b]) / 2, dr = R[a] - R[b], dg = G[a] - G[b], db = B[a] - B[b];
        return (2 + rm / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rm) / 256) * db * db;
    };
    const alive = new Uint8Array(n).fill(1), into = new Int32Array(n).fill(-1);
    const near = new Int32Array(n), nearD = new Float64Array(n);
    const findNear = i => {
        let best = -1, bd = Infinity;
        for (let j = 0; j < n; j++) if (j !== i && alive[j]) { const d = dist(i, j); if (d < bd) { bd = d; best = j; } }
        near[i] = best; nearD[i] = bd;
    };
    for (let i = 0; i < n; i++) findNear(i);
    for (let left = n; left > 255; left--) {
        let pick = -1, cost = Infinity;
        for (let i = 0; i < n; i++) if (alive[i] && cnt[i] * nearD[i] < cost) { cost = cnt[i] * nearD[i]; pick = i; }
        const to = near[pick];
        alive[pick] = 0; into[pick] = to; cnt[to] += cnt[pick];
        for (let i = 0; i < n; i++) if (alive[i] && near[i] === pick) findNear(i);
    }
    const slot = new Int32Array(n);
    const plte = [0, 0, 0];
    let next = 1;
    for (let i = 0; i < n; i++) if (alive[i]) { slot[i] = next++; plte.push(R[i], G[i], B[i]); }
    const final = i => { while (into[i] >= 0) i = into[i]; return slot[i]; };
    const raw = Buffer.alloc((w + 1) * h);
    for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
        const p = (y * w + x) * 4;
        if (data[p + 3] < 128) continue;
        raw[y * (w + 1) + 1 + x] = final(index.get((data[p] << 16) | (data[p + 1] << 8) | data[p + 2]));
    }
    // Filter 0 on every row (right for palette images); keep the smaller of two deflate strategies.
    const z = [zc.Z_DEFAULT_STRATEGY, zc.Z_FILTERED].map(strategy => deflateSync(raw, { level: 9, memLevel: 9, strategy }))
        .reduce((a, b) => (b.length < a.length ? b : a));
    const ihdr = Buffer.alloc(13);
    ihdr.writeUInt32BE(w, 0); ihdr.writeUInt32BE(h, 4); ihdr[8] = 8; ihdr[9] = 3;
    const png = Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
        chunk("IHDR", ihdr), chunk("PLTE", Buffer.from(plte)), chunk("tRNS", Buffer.from([0])), chunk("IDAT", z), chunk("IEND", Buffer.alloc(0))]);
    return { png, colours: next - 1, source: n };
}

function chunk(type, body) {
    const out = Buffer.alloc(12 + body.length);
    out.writeUInt32BE(body.length, 0);
    out.write(type, 4, "latin1");
    body.copy(out, 8);
    out.writeUInt32BE(crc(out.subarray(4, 8 + body.length)), 8 + body.length);
    return out;
}

// var: this runs from the top-level code above, before a let here would exist.
var CRC_TABLE = null;
function crc(buf) {
    if (!CRC_TABLE) {
        CRC_TABLE = new Uint32Array(256);
        for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; CRC_TABLE[n] = c >>> 0; }
    }
    let c = 0xffffffff;
    for (const b of buf) c = CRC_TABLE[(c ^ b) & 255] ^ (c >>> 8);
    return (c ^ 0xffffffff) >>> 0;
}
