// Generated by tools/pack-assets.mjs from assets/manifest.json. Do not edit.

export interface Frame { x: number; y: number; w: number; h: number; n: number }
export const FRAMES: Record<string, Frame> = {};
export const ATLAS_PNG = "";
